### ISSUE TITLE
Theme color and copy/paste

### ISSUE THREAD

**Issue by alexmigf** [richrd/suplemon#142] opened 2016-05-07 23:24 UTC
Hi,

Do you have theme colors for php files? Because i just can see some <?, array or > with color.

About copy/paste, if i select with alt or with mouse it copies the entire line when i just want some piece of the line. Do you have other solution for this?

**Comment by richrd** [comment] 2016-05-08 17:34
Hi!

Suplemon has very basic (and not very smart) line coloring built in. To get proper syntax highlighting you should install the `python3-pygments` package. That will allow suplemon to properly color most common languages.

Unfortunately the built in copy/paste can only be used on entire lines, as you noticed. For now, if you want to copy a part of a line you can just select it with the mouse and then press <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>. Then to paste it somewhere use <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>V</kbd>. Suplemon doesn't have selections yet (only cursors), and that's why it's not possible to select a part of a line to copy. I'll try and fix this in the future.

Hope this helps! :)

**Comment by alexmigf** [comment] 2016-05-08 18:36
Hi,

I have pigments installed but the color in php files is not correct with pigment demo.

The copy/paste that's ok :)

**Comment by richrd** [comment] 2016-05-09 12:02
Thanks for the screenshot!

I forgot that there's a small issue with PHP highlighting. Suplemon uses Pygments to color one line at a time, instead of coloring the whole file at once. Because of that Pygments doesn't remember that it's in a PHP block. The problem is described in issue #121 . PHP highlighting will work properly when I get that issue fixed :)

The only problem is that Pygments can't properly highlight a file that has HTML, PHP and JavaScript (or any combination of languages). It can only highlight one language at a time :( Here's an example for PHP and the same for HTML: http://pygments.org/demo/4722460/ http://pygments.org/demo/4722462/ If someone knows how to fix this please let me know!

**Comment by alexmigf** [comment] 2016-05-09 12:13
That's ok, not a major issue for me :)

**Comment by richrd** [comment] 2016-05-09 12:31
Good that it's not a show stopper :) I'll close this for now and continue in issue #121 when I have time to fix the multi line highlighting.

**Closed by richrd** 2016-05-09 12:31 UTC
