### ISSUE TITLE
OS X input handling in prompts doesn't support backspace

### ISSUE THREAD

**Issue by abl** [richrd/suplemon#61] opened 2015-06-09 21:34 UTC
I'll try to dig deeper but figured I'd post this in case it's obvious.

Normal editing works great; prompts (e.g. Save As / Exit Without Saving) do not support backspace.

Python version 3.4.3; built with Homebrew; richrd/suplemon@5913e4e9a80f4c256e7dbe0b4f1b8e4131f8b897

To reproduce, just open a file, press F1 to Save As, and attempt to backspace; nothing happens - not even a bell.

Reproduced on iTerm2 and on Apple Terminal.

**Comment by richrd** [comment] 2015-06-10 09:02
Hi! Thanks for noticing this!

I'm using curses.textpad.Textbox for handling the input queries. Seems like it doesn't recognize the key code that Macs send for backspace.

I don't have a Mac for testing right now, but I added logging in the dev branch to show what key codes are pressed in the input queries.

On Kubuntu in Konsole it gives `Query key input:263` for each backspace. Could you see what code you get for backspace?

**Comment by abl** [comment] 2015-06-10 17:31
Oh Curses. Last time I did something like this I did it with click and urwid after beating my head against curses for a day or two.

Backspace is 127 (aka ^?) and delete is 330 (aka ^[[3~). Note that some users do send ^H for backspace on OS X (there's a checkbox in both Apple Terminal and iTerm2 to support this.)

Just to make things even more fun, ^? is what is sent as delete on certain keyboard layouts. :)

**Comment by richrd** [comment] 2015-06-10 18:49
Yeah, curses isn't so much fun, but I just chose it since it's in the stdlib.

Unfortunately the input stuff sucks and I've had to cover different key variants in the key bindings. I'll do the same for the Textbox object for now to fix this :).

Later I should probably roll my own input prompt based on the Editor component. urwid seems worth checking out. I've mostly tried to seperate the UI from the logic. One day I just might implement an alternative UI with urwid.

**Comment by richrd** [comment] 2015-07-22 08:28
Hi! I finally got to this and pushed a new version to master.
I did some major refactoring and improvements, and tried to fix backspace on Mac too.

Hope it works smoothly, let me know :)

**Comment by richrd** [comment] 2015-09-06 16:36
Sorry to bother you again, but any word on this? Let me know if backspace is working properly :+1:

**Comment by richrd** [comment] 2015-09-28 20:40
Could somebody try and check this out on a Mac? I'll try and get my hands on one eventually, but that might take a while. I hope this works now.

**Comment by richrd** [comment] 2015-10-07 16:51
Update:
I've decided that I'll roll my own input prompt based on `Viewer` and `Editor` classes. (That would also resolve #95)

I'll have to do some refactoring and cleaning on them first, but after this gets done, the prompts will behave identically with the editor, which is ideal. It's a high priority issue.

**Comment by runfalk** [comment] 2016-01-11 18:51
I can confirm the current version works with backspace. However, delete (Fn+backspace) does not. There is also no visible cursor in prompts, even though it works as expected.

Python 3.5 on OS X 10.11 El Capitan, using the default Terminal App with a Gnome terminal like color theme.

(It is possible to delete the characters "Save as:" as well by using backspace. Though I assume that is not OS X specific)

**Comment by richrd** [comment] 2016-01-13 11:55
Hi, thanks for reporting! :+1: 

I'll have to implement a custom input prompt when I have time, so that it'll behave just like the editor itself. Unfortunately that change requires some refactoring, so it might take a while to get ready.

Just to recap the problems here's a list (for myself):
* Unreliable key bindings (and different from the editor)
* Prompt text can be deleted
* No visible cursor (and no multiple cursors)

**Comment by richrd** [comment] 2016-02-28 15:24
I'm closing this since the original issue is fixed. I've made great progres on the other three related problems (and #95). Hopefully I'll get these to master asap!

**Closed by richrd** 2016-02-28 15:24 UTC
Labels: bug, help wanted, priority-high
