### ISSUE TITLE
AttributeError during Closing

### ISSUE THREAD

**Issue by MultifokalHirn** [richrd/suplemon#247] opened 2019-03-06 11:02 UTC
after editing the  /private/etc/hosts file, the following happens when pressing ctrl-q:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/__main__.py", line 3, in <module>
    main()
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/cli.py", line 37, in main
    app.run()
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/main.py", line 129, in run
    self.ui.run(self.run_wrapped)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/ui.py", line 136, in run
    curses.wrapper(func)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/main.py", line 145, in run_wrapped
    self.main_loop()
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/main.py", line 198, in main_loop
    self.on_input(event)  # PERF: Up to 30% processing time
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/main.py", line 170, in on_input
    if not self.handle_input(event):
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/main.py", line 302, in handle_input
    return self.handle_key(event)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/main.py", line 323, in handle_key
    self.run_operation(operation)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/main.py", line 496, in run_operation
    result = self.operations[operation]()
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/main.py", line 379, in ask_exit
    yes = self.ui.query_bool("Exit?")
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/ui.py", line 509, in query_bool
    result = self._query(text, default, PromptBool)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/ui.py", line 495, in _query
    out = self.text_input.get_input(text, initial)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/prompt.py", line 126, in get_input
    success = self.input_loop()
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/prompt.py", line 87, in input_loop
    self.handle_input(event)
  File "/Users/username/Library/Python/3.7/lib/python/site-packages/suplemon/prompt.py", line 102, in handle_input
    if name.lower() == "y":
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by richrd** [comment] 2019-03-11 18:16
There shouldn't be anything special about editing that file. Can you remember at all what you pressed when the "Exit?" prompt came up?

**Comment by richrd** [comment] 2019-04-01 19:11
I suddenly hit this bug too. I have no idea what I pressed but it's rather annoying since it crashed  with unsaved changes. I'll look into this and see about fixing it when my broken hand recovers.

**Comment by richrd** [comment] 2019-06-05 05:00
I was able to reproduce this and a fix will be included in the next release.

**Closed by richrd** 2019-06-05 05:00 UTC
Labels: bug
