### ISSUE TITLE
_curses.error: addwstr() on Ubuntu 17.04

### ISSUE THREAD

**Issue by wjrivera** [richrd/suplemon#187] opened 2017-05-01 14:53 UTC
I'm getting this error after installing suplemon:
`Traceback (most recent call last):
  File "/usr/local/bin/suplemon", line 11, in <module>
    load_entry_point('Suplemon==0.1.60', 'console_scripts', 'suplemon')()
  File "/usr/local/lib/python3.5/dist-packages/suplemon/cli.py", line 37, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/suplemon/main.py", line 124, in run
    self.ui.run(self.run_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/suplemon/ui.py", line 128, in run
    curses.wrapper(func)
  File "/usr/lib/python3.5/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/suplemon/main.py", line 138, in run_wrapped
    self.ui.refresh()
  File "/usr/local/lib/python3.5/dist-packages/suplemon/ui.py", line 277, in refresh
    self.refresh_status()
  File "/usr/local/lib/python3.5/dist-packages/suplemon/ui.py", line 298, in refresh_status
    self.show_top_status()
  File "/usr/local/lib/python3.5/dist-packages/suplemon/ui.py", line 335, in show_top_status
    self.header_win.addstr(0, 0, head, curses.color_pair(0))
_curses.error: addwstr() returned ERR
`
Help? Thanks

Python3 - 3.5.3
Python - 2.7.13
pip3 - 9.0.1
Ubuntu 17.04

**Comment by richrd** [comment] 2017-05-02 14:58
Does it completely crash and not run at all, or is the error printed out when you exit the editor?

Also what method did you use to install suplemon?

**Comment by wjrivera** [comment] 2017-05-02 15:10
When i run `suplemon sample.c`, i get the error above and does not run the program at all (As in `ps aux | grep suplemon` does not show anything).
The steps I took were cloning the repo from git, installed suplemon from pip3, then running the script setup.py install with python3.
Was that the correct way?

**Comment by richrd** [comment] 2017-05-03 06:31
You only need to run the setup.py OR the pip3 install, but it shouldnt matter if you did both. I can confirm this error on a fresh ubuntu 17.04 virtual machine. I'll try to fix this asap and get back to you!

**Comment by richrd** [comment] 2017-05-05 17:45
The reason it crashes is because suplemon uses special unicode characters in the top status row. It used to work on ubuntu 16, so I don't know what broke it on ubuntu 17. Anyway, as a quick fix you can create a file `~/.config/suplemon/suplemon-config.json` and add this into it:
```{
    "app": {
        "use_unicode_symbols": 0
    }
}```

**Comment by wjrivera** [comment] 2017-05-05 18:18
Perfect, it works fine.  Thank you!!!

**Comment by Xedecimal** [comment] 2017-06-21 17:17
I'm not sure why this was closed, it's not actually fixed. This workaround seems to work but that means anyone on Ubuntu 17 is going to need to do this in order to do anything and that would be a huge turnoff for new users.

**Comment by richrd** [comment] 2017-06-21 18:37
Good catch! Yeah, it wasn't actually fixed before this got closed. However I actually decided to release a new version solely to change the default setting. So it did get fixed, see this line: https://github.com/richrd/suplemon/blob/master/suplemon/config/defaults.json#L22

**Comment by wjrivera** [comment] 2017-06-21 19:33
I apologized for closing it, my fault

**Comment by Xedecimal** [comment] 2017-06-21 19:43
Thank you, it'd be nice to get those back, I read around a bit and found things like https://stackoverflow.com/questions/32293981/curses-error-addstr-returned-err and https://ubuntuforums.org/showthread.php?t=457689 and http://bugs.python.org/issue8243 and https://github.com/michael-lazar/rtv/issues/316 there may be some workarounds, that way Ubuntu users may keep their watch, battery and other icons. Would be nice to grow on it too while on the subject, check out https://github.com/gabrielelana/awesome-terminal-fonts

**Comment by richrd** [comment] 2017-06-22 15:49
I've noticed that curses gives errors when trying to write off screen. It even shits itself when writing a character to the bottom right corner (though that does work despite the error). Seems to me that the wide unicode characters are counted as two separate characters by curses thus making it think the string is too long.

Seems like I'll just have to wrap addstr in a try/except to make this work (just tested that sucessfully).

**Comment by richrd** [comment] 2017-06-22 16:27
Well shit. The try/except introduces a new problem. Weird artifacts:
![image](https://user-images.githubusercontent.com/3417292/27444929-a6b695b0-5780-11e7-8aa3-6461171dac9c.png)

Not sure if this makes it any better. Why oh why did this have to break with Ubuntu 17 :disappointed:

**Comment by richrd** [comment] 2017-06-27 12:21
I tried this with gnome-terminal and it handles the special symbols fine. However KDE's konsole doesn't. :thinking:

**Comment by richrd** [comment] 2017-08-20 17:33
Oh well. Pretty clear that there's nothing I can do about this. It's a KDE Konsole bug that affects anything running in the terminal.
See: https://bugs.kde.org/show_bug.cgi?id=361547

**Comment by richrd** [comment] 2017-08-20 17:38
Forgot what the issue was actually about. Reopen.

**Comment by richrd** [comment] 2017-09-24 12:06
Would someone like to test v0.1.62 via the dev branch to see if this works as intended now?

**Comment by richrd** [comment] 2017-09-25 16:45
Just released v0.1.62 with a fix for this issue.

**Comment by richrd** [comment] 2017-10-02 22:55
Closing. Please reopen if problem persists.

**Closed by richrd** 2017-10-02 22:55 UTC
Labels: bug
