### ISSUE TITLE
Python idioms

### ISSUE THREAD

**Issue by Gnewbee** [richrd/suplemon#195] opened 2017-09-10 21:47 UTC
Some things may be made more pythonic (all of which I'm offering to work on):
    - Use enumerate instead of a discreet variable, i.e. instead of:
```python
i = 0
# First match files beginning with s
for file in self.files:
    if file.name.lower().startswith(s):
        return i
    i += 1
```
    do:
```python
for i, file in enumerate(self.files):
    if file.name.lower().startswith(s):
        return i
```
    - Use of True/False vs 1/0
    - Ensure attributes are defined in constructor
    - Use properties instead of simple getters & setters

**Comment by richrd** [comment] 2017-09-21 06:56
You're right! If you have time I would be very grateful if you could submit improvements to these issues. I'm sure I'll learn some new stuff (like I already did from this issue) :slightly_smiling_face:

**Comment by richrd** [comment] 2017-09-25 17:12
Oh, I forgot to mention, if you do submit a Pull Request, submit it against the dev branch. Master is only for new versions.

**Comment by Gnewbee** [comment] 2017-10-05 12:15
What is the difference between rewrite-dev and dev (i.e. which should I prefer to pull request to for which kind of work)?

**Comment by richrd** [comment] 2017-10-06 07:42
It's a big difference, the `dev` branch is for developing the current codebase and new features and versions. It should be used for pull requests.

The `rewrite-dev` is an entirely new codebase where I'm rewriting the entire architecture of suplemon to be more robust and flexible. It includes things like a curses backend abstraction, layout engine, and better text manipulation etc. All of it is work in progress and new working features are merged from `rewrite-dev` to `rewrite-stable`. Currently both rewrite branches are unusable as most features haven't been implemented yet. The app starts but you can't do anything at all with it yet.

**Comment by Gnewbee** [comment] 2017-10-18 21:26
I'm in the process of implementing the changes. I'd like to know if I can change display["show_top_bar"], display["show_bottom_bar"] and display["show_legend"] to true/false instead of integers in prompt.py.
Also, self.pygments_syntax.startinline = 1 in viewer.py and self.warned_old_curses = 0 in ui.py

**Comment by richrd** [comment] 2017-10-20 10:19
Those changes should be fine, the intent of them is to be boolean flags. Thanks! :+1:

**Comment by Gnewbee** [comment] 2017-10-22 18:46
OK, I've implemented these. I'm currently on the last point (getters, setters). I've made notes of the changes I plan but I wanted to confirm with you. There are accessor methods that seem to have been implemented preemptively (like BaseViewer.get_y_scroll and get_x_scroll or in Cursor) and are never called or do not have any real need to exist. In python, because of property decorators, this is considered an antipattern and accessors/mutators should be implemented only when required (when they do more than simple access and set) through properties. Is it OK if I remove these ?

**Comment by twolfson** [comment] 2017-10-22 23:10
I feel I should counterpoint that sometimes using `get_*` instead of `@get`/`@set` is preferable. This scenario is usually caused by the method itself being high cost (e.g. needs to do something higher than `O(1)`) whereas accessing a method like a property can make it look like `O(1)` or a static value

**Comment by Gnewbee** [comment] 2017-10-23 10:13
I agree with you that if there is a substantial amount of code behind the accessor, making an accessor makes sense because it makes it more explicit that it is indeed a function and might take time to compute.
What I was arguing above, is that it is considered an antipattern in python (contrary e.g. to Java) to create an accessor/mutator only to do:

``` python
def get_x(self):
    return self.x

def set_x(self, x):
    self.x = x
```
Properties are here to replace the need to create these for potential future use.
I do not want to remove all accessors/mutators but some here are even not used at all. Also, some like in the Cursor class only follow the above pattern.

**Comment by richrd** [comment] 2017-10-24 09:37
You're right! I didn't know about `@property` when I wrote those, and my motivation was that I might need to add some logic or validation to them in the future. They could be removed and if some special implementation is needed later `@property` can be used.

**Closed** 2017-12-25 13:30 UTC
Labels: code-style
